version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[actions]"

  # Maintain dependencies for Git Submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[submodule]"

  # Maintain dependencies for online document support (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm]"

  # Maintain dependencies for ECL Watch (npm)
  - package-ecosystem: "npm"
    directory: "/esp/src"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm]"

  # Maintain dependencies for docker images (docker)
  - package-ecosystem: "docker"
    directory: "/dockerfiles"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[docker]"

  - package-ecosystem: "docker"
    directory: "/dockerfiles/vcpkg"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[docker]"

  - package-ecosystem: "docker"
    directory: "/dockerfiles/vcpkg/platform-core-ubuntu-22.04"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[docker]"
