name: Test Build

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,read"
  VCPKG_NUGET_REPOSITORY: "https://github.com/hpcc-systems/vcpkg"
  OS_DEPENDENCIES: "bison flex build-essential binutils-dev curl lsb-release libcppunit-dev python3-dev default-jdk
    r-base-dev r-cran-rcpp r-cran-rinside r-cran-inline pkg-config libtool autotools-dev automake git cmake"

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        options:
          - 'ubuntu-23.10'
          - 'ubuntu-22.04'
          - 'ubuntu-20.04'
          - 'centos-8'
          - 'centos-7'
          - 'amazonlinux'
        description: 'Operating System'
        required: false
        default: 'ubuntu-22.04'
      ln:
        type: boolean
        description: 'Internal Build'
        required: false
        default: false
      smoketest:
        type: boolean
        description: 'Run Smoketest'
        required: false
        default: false

  # Do not include "push" in final version
  push:

  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.10.*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

  schedule:
    - cron: "0 0 * * *"

jobs:
  build-workflow-dispatch:
    if: ${{ contains('workflow_dispatch', github.event_name) }}
    uses: ./.github/workflows/build-docker.yml
    with:
      os: ${{ inputs.os }}
      ln: ${{ inputs.ln }}
      upload-package: true
      asset-name: 'docker-package'
    secrets: inherit

  test-workflow-dispatch:
    if: ${{ contains('workflow_dispatch', github.event_name) && inputs.smoketest == true }}
    needs: build-workflow-dispatch
    uses: ./.github/workflows/test-smoke-gh_runner.yml
    with:
      os: ${{ inputs.os }}
      asset-name: 'docker-package'
    secrets: inherit

  build-docker-ubuntu-23_10:
    if: ${{ contains('pull_request,push', github.event_name) }}
    uses: ./.github/workflows/build-docker.yml
    with:
      os: ubuntu-23.10
      single-package: true
      containerized: false
    secrets: inherit

  build-docker-ubuntu-22_04:
    if: ${{ contains('pull_request,push', github.event_name) }}
    uses: ./.github/workflows/build-docker.yml
    with:
      os: ubuntu-22.04
      single-package: true
      containerized: false
      upload-package: true
      asset-name: 'docker-package'
    secrets: inherit

  test-smoke-docker-ubuntu-22_04:
    if: ${{ contains('pull_request,push', github.event_name) }}
    needs: build-docker-ubuntu-22_04
    uses: ./.github/workflows/test-smoke-gh_runner.yml
    with:
      os: ubuntu-22.04
      asset-name: 'docker-package'
    secrets: inherit

  test-unit-docker-ubuntu-22_04:
    if: ${{ contains('pull_request,push', github.event_name) }}
    needs: build-docker-ubuntu-22_04
    uses: ./.github/workflows/test-unit-gh_runner.yml
    with:
      os: ubuntu-22.04
      asset-name: 'docker-package'
    secrets: inherit

  test-ui-docker-ubuntu-22_04:
    if: ${{ contains('pull_request,push', github.event_name) }}
    needs: build-docker-ubuntu-22_04
    uses: ./.github/workflows/test-ui-gh_runner.yml
    with:
      os: ubuntu-22.04
      asset-name: 'docker-package'
    secrets: inherit

  build-docker-ubuntu-20_04:
    if: ${{ contains('schedule,push', github.event_name) }}
    uses: ./.github/workflows/build-docker.yml
    with:
      os: ubuntu-20.04
      single-package: true
      containerized: false
    secrets: inherit

  build-docker-centos-8:
    if: ${{ contains('schedule,push', github.event_name) }}
    uses: ./.github/workflows/build-docker.yml
    with:
      os: centos-8
      single-package: true
      containerized: false
    secrets: inherit

  build-docker-centos-7:
    if: ${{ contains('pull_request,push', github.event_name) }}
    uses: ./.github/workflows/build-docker.yml
    with:
      os: centos-7
      single-package: true
      containerized: false
      cmake-configuration-ex: "-DVCPKG_TARGET_TRIPLET=x64-centos-7-dynamic"
    secrets: inherit

  build-docker-amazonlinux:
    if: ${{ contains('schedule,push', github.event_name) }}
    uses: ./.github/workflows/build-docker.yml
    with:
      os: amazonlinux
      single-package: true
      containerized: false
      cmake-configuration-ex: "-DVCPKG_TARGET_TRIPLET=x64-amazonlinux-dynamic"
    secrets: inherit

  build-gh_runner-ubuntu-22_04:
    if: ${{ contains('pull_request,push', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: ubuntu-22.04
      single-package: true
      containerized: false
      upload-package: true
      asset-name: 'gh_runner-package'
    secrets: inherit
  
  test-smoke-gh_runner-ubuntu-22_04:
    if: ${{ contains('pull_request,push', github.event_name) }}
    needs: build-gh_runner-ubuntu-22_04
    uses: ./.github/workflows/test-smoke-gh_runner.yml
    with:
      os: ubuntu-22.04
      asset-name: 'gh_runner-package'
    secrets: inherit

  test-unit-gh_runner-ubuntu-22_04:
    if: ${{ contains('pull_request,push', github.event_name) }}
    needs: build-gh_runner-ubuntu-22_04
    uses: ./.github/workflows/test-unit-gh_runner.yml
    with:
      os: ubuntu-22.04
      asset-name: 'gh_runner-package'
    secrets: inherit

  test-ui-gh_runner-ubuntu-22_04:
    if: ${{ contains('pull_request,push', github.event_name) }}
    needs: build-gh_runner-ubuntu-22_04
    uses: ./.github/workflows/test-ui-gh_runner.yml
    with:
      os: ubuntu-22.04
      asset-name: 'gh_runner-package'
    secrets: inherit

  build-gh_runner-ubuntu-20_04:
    if: ${{ contains('schedule,push', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: ubuntu-20.04
      single-package: true
      containerized: false
    secrets: inherit

  build-gh_runner-windows-2022:
    if: ${{ contains('pull_request,push', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: windows-2022
      single-package: true
      containerized: false
      cmake-configuration: '-T host=x64 -A x64 -DUSE_OPTIONAL=OFF -DCLIENTTOOLS_ONLY=ON -DUSE_AZURE=OFF -DUSE_CASSANDRA=OFF -DUSE_JAVA=OFF -DUSE_OPENLDAP=OFF'
    secrets: inherit

  build-gh_runner-windows-2019:
    if: ${{ contains('schedule,push', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: windows-2019
      single-package: true
      containerized: false
      cmake-configuration: '-T host=x64 -A x64 -DUSE_OPTIONAL=OFF -DCLIENTTOOLS_ONLY=ON -DUSE_AZURE=OFF -DUSE_JAVA=OFF -DUSE_OPENLDAP=OFF'
    secrets: inherit

  build-gh_runner-macos-12:
    if: ${{ contains('pull_request,push', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: macos-12
      single-package: true
      containerized: false
      build-type: 'Release'
      cmake-configuration: '-DUSE_OPTIONAL=OFF -DCLIENTTOOLS_ONLY=ON -DUSE_AZURE=OFF -DUSE_CASSANDRA=OFF -DUSE_JAVA=OFF -DUSE_OPENLDAP=OFF'
    secrets: inherit

  build-gh_runner-macos-11:
    if: ${{ contains('schedule,push', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: macos-11
      single-package: true
      containerized: false
      build-type: 'Release'
      cmake-configuration: '-DUSE_OPTIONAL=OFF -DCLIENTTOOLS_ONLY=ON -DUSE_AZURE=OFF -DUSE_CASSANDRA=OFF -DUSE_JAVA=OFF -DUSE_OPENLDAP=OFF'
    secrets: inherit
