name: Build and publish
# This workflow is triggered on new tags of Community Edition 7.8.x or later,
# or any of the weekly tag names starting 'master'
on:
  push:
    tags:
    - 'tmp_sign'

jobs:
  build:
    name: "Build and publish release container"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./dockerfiles
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          latest: 0   # this should only be set on the current minor branch


