name: smoketest-vcpkg

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-8.6.*"
      - "!candidate-8.4.*"
      - "!candidate-8.2.*"
      - "!candidate-8.0.*"
      - "!candidate-7.*"
      - "!candidate-6.*"

jobs:
  check-skip:
    runs-on: ubuntu-20.04
    outputs:
      platform: ${{ steps.skip_check.outputs.platform }}
    steps:
      - id: skip_check
        uses: hpcc-systems/github-actions/changed-modules@main
        with:
          github_token: ${{ github.token }}

  vcpkg-cache:
    name: "Fetch / Create vcpkg packages"
    # needs: check-skip
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: "src"

      - name: docker-build vcpkg-configure
        shell: "bash"
        run: |
          mkdir build
          docker build --pull --rm -f "./src/dockerfiles/vcpkg/configure/Dockerfile" -t vcpkg-configure:latest \
            --build-arg UID=$(id -u) \
            --build-arg GID=$(id -g) \
            --build-arg GITHUB_OWNER=${{ github.repository_owner }} \
            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            "./src"

      - name: docker-run vcpkg-configure
        shell: "bash"
        run: |
          docker run -u $(id -u):$(id -g) --rm \
            -v ${PWD}/build:/build \
            -v ${PWD}/src:/src \
            vcpkg-configure:latest

      - name: docker-build vcpkg-build
        shell: "bash"
        run: |
          docker build --pull --rm -f "./src/dockerfiles/vcpkg/build/Dockerfile" -t vcpkg-build:latest \
            --build-arg UID=$(id -u) \
            --build-arg GID=$(id -g) \
            --build-arg GITHUB_OWNER=${{ github.repository_owner }} \
            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            "./src"

      - name: docker-run vcpkg-build
        shell: "bash"
        run: |
          docker run  -u $(id -u):$(id -g) --rm \
            -v ${PWD}/build:/build \
            -v ${PWD}/src:/src \
            vcpkg-build:latest

      - name: docker-build vcpkg-test
        shell: "bash"
        run: |
          docker build --pull --rm -f "./src/dockerfiles/vcpkg/test/Dockerfile" -t vcpkg-test:latest \
            --build-arg UID=$(id -u) \
            --build-arg GID=$(id -g) \
            --build-arg GITHUB_OWNER=${{ github.repository_owner }} \
            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            "./src"

      - name: docker-run vcpkg-test
        shell: "bash"
        run: |
          docker run --rm \
            -v ${PWD}/build:/build \
            -v ${PWD}/src:/src \
            vcpkg-test:latest
