name: smoketest-vcpkg

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-8.6.*"
      - "!candidate-8.4.*"
      - "!candidate-8.2.*"
      - "!candidate-8.0.*"
      - "!candidate-7.*"
      - "!candidate-6.*"

jobs:
  check-skip:
    runs-on: ubuntu-20.04
    outputs:
      platform: ${{ steps.skip_check.outputs.platform }}
    steps:
      - id: skip_check
        uses: hpcc-systems/github-actions/changed-modules@main
        with:
          github_token: ${{ github.token }}

  vcpkg-cache:
    name: "Fetch / Create vcpkg packages"
    needs: check-skip
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Checkout submodule vcpkg
        shell: "bash"
        run: |
          git submodule update --init --recursive ./vcpkg

      - name: vcpkg hash
        run: |
          echo "VCPKG_SHA=$(git -C ./vcpkg rev-parse HEAD)" >> $GITHUB_ENV

      - name: Test
        run: echo ${{ env.VCPKG_SHA }}

      - name: setup vcpkg cache
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: ./vcpkg-cache/**/*
          key: vcpkg-${{ env.VCPKG_SHA }}
          restore-keys: |
            vcpkg-

      - name: docker vcpkg install
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        shell: "bash"
        run: |
          docker build --pull --rm -f "dockerfiles/vcpkg/install/Dockerfile" -t vcpkg-install:latest "."
          docker run --rm \
            -v ${PWD}/vcpkg-cache:/vcpkg-cache \
            vcpkg-install:latest

  build:
    name: "Build HPCC-Platform"
    needs: vcpkg-cache
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: vcpkg hash
        run: |
          echo "VCPKG_SHA=$(git -C ./vcpkg rev-parse HEAD)" >> $GITHUB_ENV

      - name: platform vcpkg cache
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: ./vcpkg-cache/**/*
          key: vcpkg-${{ env.VCPKG_SHA }}-${{ hashFiles('./vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ env.VCPKG_SHA }}
            vcpkg-

      - name: docker vcpkg configure
        shell: "bash"
        run: |
          docker build --pull --rm -f "dockerfiles/vcpkg/configure/Dockerfile" -t vcpkg-configure:latest "."
          docker run --rm \
            -v ${PWD}/.:/hpcc-source \
            vcpkg-configure:latest

      - name: docker vcpkg build
        shell: "bash"
        run: |
          docker build --pull --rm -f "dockerfiles/vcpkg/build/Dockerfile" -t vcpkg-build:latest "."
          docker run --rm \
            -v ${PWD}:/hpcc-source \
            vcpkg-build:latest

      - uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: ./build/*.deb

  test:
    name: "Test HPCC-Platform"
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/download-artifact@v3
        with:
          name: deb-package
          path: ./build/*.deb

      - name: install
        shell: "bash"
        run: |
          sudo dpkg -i ./build/*.deb
          apt-get -yq install -f

      - name: start
        shell: "bash"
        run: |
          sudo /etc/init.d/hpcc-init start
