name: smoketest-vcpkg

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-8.6.*"
      - "!candidate-8.4.*"
      - "!candidate-8.2.*"
      - "!candidate-8.0.*"
      - "!candidate-7.*"
      - "!candidate-6.*"

jobs:
  check-skip:
    runs-on: ubuntu-20.04
    outputs:
      platform: ${{ steps.skip_check.outputs.platform }}
    steps:
      - id: skip_check
        uses: hpcc-systems/github-actions/changed-modules@main
        with:
          github_token: ${{ github.token }}

  vcpkg-cache:
    name: "Fetch / Create vcpkg packages"
    # needs: check-skip
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          submodules: true
          path: "src"

      - name: docker vcpkg configure
        shell: "bash"
        run: |
          docker build --pull --rm -f "./src/dockerfiles/vcpkg/configure/Dockerfile" -t vcpkg-configure:latest \
          --build-arg GITHUB_OWNER=${{ github.repository_owner }} \
          --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          "."
          mkdir build
          docker run --rm \
            -v ${PWD}/build:/build \
            -v ${PWD}/src:/src \
            vcpkg-configure:latest

      - name: docker vcpkg build
        shell: "bash"
        run: |
          docker build --pull --rm -f "./src/dockerfiles/vcpkg/build/Dockerfile" -t vcpkg-build:latest "."
          docker run --rm \
            -v ${PWD}/build:/build \
            -v ${PWD}/src:/src \
            vcpkg-build:latest

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: deb-package
  #         path: ./build/*.deb

  # test:
  #   name: "Test HPCC-Platform"
  #   needs: build
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Check out source code
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: recursive

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: deb-package
  #         path: ./build/*.deb

  #     - name: install
  #       shell: "bash"
  #       run: |
  #         sudo dpkg -i ./build/*.deb
  #         apt-get -yq install -f

  #     - name: start
  #       shell: "bash"
  #       run: |
  #         sudo /etc/init.d/hpcc-init start
