name: Unittest Package (gh-runner)

on:
  workflow_call:
    inputs:
      os:
        type: string
        description: 'Operating System'
        required: false
        default: 'ubuntu-22.04'
      asset-name:
        type: string
        description: 'Asset Name'
        required: false
        default: 'build-docker-package'
      dependencies:
        type: string
        description: 'Dependencies'
        required: false
        default: 'bison flex build-essential binutils-dev curl lsb-release libcppunit-dev python3-dev default-jdk r-base-dev r-cran-rcpp r-cran-rinside r-cran-inline pkg-config libtool autotools-dev automake git cmake xmlstarlet'

jobs:

  main:
    runs-on: ${{ inputs.os }}
    steps:

      - name: Download Package
        uses: actions/download-artifact@v3
        with:
            name: ${{ inputs.asset-name }}
            path: ${{ inputs.asset-name }}

      - name: Install Dependencies
        shell: "bash"
        run: |
            sudo apt-get update
            sudo apt-get install -y ${{ inputs.dependencies }}
            sudo apt-get install -y gdb

            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs

            echo "node.js version = $(node --version), npm version = $(npm --version), release = $(lsb_release -sc)"

      - name: Install Package
        shell: "bash"
        run: |
            sudo apt-get install -y -f ./${{ inputs.asset-name }}/*.deb
            sudo chown -R $USER:$USER /opt/HPCCSystems

      - name: Run Tests
        timeout-minutes: 10 # generous, expected time is approx 1 min.
        shell: "bash"
        run: |
          export LANG="en_US.UTF-8"
          sudo update-locale
          /opt/HPCCSystems/bin/unittests
